### ISSUE TITLE
Catalogue Implementation Tracker

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-apocalypse#9]
Please check-mark when your cat is done!

- [x] Library - Aeldari Weapons.cat - @WindstormSCR 
- [x] Library - Chaos Space Marines.cat - @Mad-Spy 
- [x] Library - Space Marines.cat - @Thairne, @Mad-Spy
- [x] Library - Astra Militarum.cat - @GenWilhelm 
- [x] Library - Weapons.cat
- [x] Aeldari -   Craftworlds.cat -  @WindstormSCR 
- [x] Aeldari - Drukhari.cat - @WindstormSCR 
- [x] Aeldari - Harlequins.cat  - @WindstormSCR 
- [x] Aeldari - Ynnari.cat - @WindstormSCR 
- [x] Chaos - Chaos Knights.cat - @Mad-Spy 
- [x] Chaos - Chaos Titans.cat - @Mad-Spy 
- [x] Chaos - Death Guard.cat - @Mad-Spy 
- [x] Chaos - Gellerpox Infected.cat - @Mad-Spy 
- [x] Chaos - Heretic Astartes.cat - @Mad-Spy 
- [x] Chaos - Legiones Daemonica.cat - @Mad-Spy 
- [x] Chaos - Renegades and Heretics - @Mad-Spy 
- [x] Chaos - Thousand Sons.cat - @Mad-Spy 
- [x] Imperium - Adeptus Astartes.cat - @Mad-Spy 
- [x] Imperium - Adeptus Custodes.cat - @Mad-Spy 
- [x] Imperium - Adeptus Mechanicus.cat - @Thairne
- [x] Imperium - Adeptus Ministorum.cat - @Mad-Spy 
- [x] Imperium - Agents of the Imperium.cat - @Mad-Spy 
- [x] Imperium - Astra Militarum.cat - @GenWilhelm 
- [x] Imperium - Blood Angels.cat - @Mad-Spy 
- [x] Imperium - Dark Angels.cat - @Thairne
- [x] Imperium - Death Korps of Krieg.cat - @GenWilhelm 
- [x] Imperium - Deathwatch.cat - @Mad-Spy 
- [x] Imperium - Elysians.cat - @GenWilhelm 
- [x] Imperium - Grey Knights.cat - @Mad-Spy 
- [x] Imperium - Imperial Knights.cat - @DrTobogganMD 
- [x] Imperium - Space Wolves.cat - @Mad-Spy
- [x] Imperium - Titan Legions.cat - @DrTobogganMD 
- [x] Necrons.cat -  @DrTobogganMD 
- [x] Orks.cat - @DrTobogganMD
- [x] T'au Empire.cat - @amis92 
- [x] Tyranids - Genestealer Cults.cat - @GenWilhelm 
- [x] Tyranids - Hive Fleets.cat - @GenWilhelm 
- [x] Unaligned.cat - @Mad-Spy

**Comment by Mad-Spy** [comment]
All catalogues complete for release.
